### ISSUE TITLE
Kick off raster-vision predict job on Batch

### ISSUE THREAD

**Issue by lewfish** [raster-foundry/raster-foundry-python-client#29]

**Comment by jisantuc** [comment]
This should be mediated by the Raster Foundry API I think, right?

**Comment by notthatbreezy** [comment]
I think that's where we are headed, this is a step in that direction kind of -- idea for this is that given a project and other information, the python client can craft the correct command to invoke predictions in a project.

**Comment by lewfish** [comment]
In the future, we will probably want to write a row to a database table to associate the project ID, trained model URI, raster-vision commit, and predictions URI. We might also want a field to represent the status of the Batch job, and some mechanism for polling to update this field.
